version: "3.8"

services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      - shared

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

    labels:
      - traefik.enable=true
      - traefik.docker.network=shared
      - traefik.http.routers.prometheus.rule=Host(`traefik.azure.icu`) && PathPrefix(`/prometheus`)
      - traefik.http.routers.prometheus.entrypoints=websecure
      - traefik.http.routers.prometheus.tls.certresolver=letsencrypt

    volumes:
      - ./prometheus:/etc/prometheus

  # grafana:
  #   image: grafana/grafana:main
  #   container_name: grafana

networks:
  shared:
    name: shared
