version: "3.8"

services:
  prometheus:
    image: prom/prometheus:main
    container_name: prometheus
    restart: always
    ports:
      - 9090:9090
    networks:
      - shared

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

    volumes:
      - ./prometheus:/etc/prometheus

  grafana:
    image: grafana/grafana-oss:main
    container_name: grafana
    restart: always
    networks:
      - shared

    labels:
      - traefik.enable=true
      - traefik.docker.network=shared
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.rule=Host(`${GRAFANA_URL}`)
      - traefik.http.routers.grafana.entrypoints=websecure
      - traefik.http.routers.grafana.tls.certresolver=letsencrypt

networks:
  shared:
    name: shared
