services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=shared
      - traefik.http.services.n8n.loadbalancer.server.port=5678
      - traefik.http.routers.n8n.rule=Host(`${N8N_URL}`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=letsencrypt
    environment:
      - N8N_HOST=${N8N_URL}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${N8N_URL}/
      - GENERIC_TIMEZONE=${N8N_GENERIC_TIMEZONE}
    volumes:
      - ./n8n:/home/node/.n8n
    networks:
      - shared
      - n8n-internal

  n8n-mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=n8n
    volumes:
     - ./mongo:/data/db
    networks:
      - n8n-internal

networks:
  shared:
    name: shared
  n8n-internal:
    internal: true