version: "3.9"
services:
  keycloak:
    image: keycloak/keycloak
    restart: always
    env_file: .env
    command:
      - "start --hostname=${KEYCLOAK_HOSTNAME}"
    networks:
      - shared
      - keycloak_internal
    labels:
      - traefik.enable=true
      - traefik.docker.network=shared
      - traefik.http.services.keycloak.loadbalancer.server.port=8080
      - traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_HOSTNAME}`)
      - traefik.http.routers.keycloak.entrypoints=websecure
      - traefik.http.routers.keycloak.tls.certresolver=letsencrypt

  keycloak-db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - keycloak_internal

networks:
  shared:
    external: true
  keycloak_internal:
    internal: true