version: "3.9"

services:
  gotosocial:
    image: superseriousbusiness/gotosocial:latest
    container_name: gotosocial
    user: ${GTS_USER}
    volumes:
      - ./gotosocial/data:/gotosocial/storage
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=shared
      - traefik.http.services.gotosocial.loadbalancer.server.port=8080
      - traefik.http.routers.gotosocial.rule=Host(`${GTS_HOST}`)
      - traefik.http.routers.gotosocial.entrypoints=websecure
      - traefik.http.routers.gotosocial.tls.certresolver=letsencrypt
    restart: "always"
    networks:
      - shared

networks:
  shared:
    external: true