version: "3.9"

services:
  kuma:
    image: louislam/uptime-kuma:1
    container_name: kuma
    restart: always
    volumes:
      - ./kuma:/app/data
    env_file:
      - .env
    labels:
      - traefik.enable=true
      - traefik.docker.network=shared
      - traefik.http.services.kuma.loadbalancer.server.port=3001
      - traefik.http.routers.kuma.rule=Host(`${KUMA_URL}`)
      - traefik.http.routers.kuma.entrypoints=websecure
      - traefik.http.routers.kuma.tls.certresolver=letsencrypt
    networks:
      - shared

networks:
  shared:
    external: true
