services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    restart: always
    stop_grace_period: 1m

    # domain
    hostname: mail
    domainname: azure.icu

    ports:
      - "25:25" # outbound smtp
      - "587:587" # inbound smtp

    environment:
      - SSL_TYPE=letsencrypt
      - SSL_DOMAIN=mail.azure.icu
    volumes:
      - ../traefik/letsencrypt/acme.json:/etc/letsencrypt/acme.json:ro
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro

    cap_add:
      - NET_ADMIN

    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0

  whoami:
    image: traefik/whoami:latest
    labels:
      - traefik.enable=true
      - traefik.docker.network=shared
      - traefik.http.routers.whoami.rule=Host(`mail.example.com`)
      - traefik.http.routers.whoami.entrypoints=websecure
      - traefik.http.routers.whoami.tls.certresolver=letsencrypt
