version: "3.9"
services:
  db:
    container_name: soapbox-db
    image: postgres:15-alpine
    restart: always
    env_file: .env
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 54321:5432
    networks:
      - shared

networks:
  shared:
    external: true